### PR TITLE
feature/xkcd: barebone xkcd discord embed implementation

### PR DESCRIPTION
**Pull request by bitnahian**
Basic implementation of xkcd utility. 

Example:

Usage: $xkcd

image

Built using [discord.Embed](https://discordpy.readthedocs.io/en/latest/api.html#embed) class, which provides an easy to use template.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @bitnahian I found some things in the your PR.

- modules/xkcd.py is not imported by the bot
- All the logic for the feature is in the bot.py file.

Moving the logic to a method in "modules/xkcd.py" that returns the `embed` dict and calling in from bot.py would help keep the code organized.

Everything else looks good and runs fine.

**Comment by bitnahian** [comment]
Yes. This was just the barebone implementation without modularising it much. Just wanted the thumbs up before putting it in a module.

**Comment by bitnahian** [comment]
Okay, I've modularised the code.

**Comment by ghost** [comment]
Everything looks good to me. I'll ask @swapagarwal and he should merge this soon :tada:

**Comment by swapagarwal** [comment]
@bitnahian What are the changes to `requirements.txt`?
It's not visible in the `files` tab.

**Comment by bitnahian** [comment]
Don't understand why it's a binary file. Changes are adding python-dotenv to the requirements.

**Comment by ghost** [comment]
@bitnahian line 6 of your requirements.txt is:
`discord.py==1.0.0a1634+g7f4c57d`
Instead of:
`git+git://github.com/Rapptz/discord.py@rewrite#egg=discord.py`

I think this might have caused the problem...

**Comment by bitnahian** [comment]
I've changed that line. Thanks for the correction. I thought a simple pip freeze would do.

**Review by swapagarwal — APPROVED** [review]
Awesome work! 💯
Thanks for your contribution. 🔥

**Pull request merged**
