### PR TITLE
flip_a_coin function added

### PR DESCRIPTION
**Pull request by sayanmondal2098**

### CODE REVIEW

**Comment by mboekhold** [comment]
Hey @sayanmondal2098 , import a package called black and run `black .` to fix the formatting

**Comment by sayanmondal2098** [comment]
flip a coin added and reformated

**Comment by mboekhold** [comment]
black works with the most recent version of pep8 compliance, these additions were not made in the pep8 package. this package has been renamed to pycodestyle. see: https://pypi.org/project/pycodestyle/ and the reason why this has been changed here: https://github.com/PyCQA/pycodestyle/issues/466

**Comment by swapagarwal** [comment]
Let's keep this PR aimed at adding a module. 😅
Right now, it does other things like changing `'` to `"` and other formatting changes.

**Comment by mboekhold** [comment]
@sayanmondal2098 as @swapagarwal  said, please keep your PR solely for the flip_a_coin module, if you want to merge a new module, create a new branch and then a new PR.

**Comment by swapagarwal** [comment]
Also, remove the formatting changes and set the line-length to 120 in your local editor.

**Comment by swapagarwal** [comment]
Ideally, there would be 3 files changed (right now, you have 10!).

**Pull request closed without merging**
