### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by StylPamp**
Added roll,ping_google,weather,time_in,joke,quote,fact,flip_a_coin features.
Images at 'images' folder.
Quotes,jokes,facts at 'data' folder.
We couldn't contact you so we didn't know what exactly we had to upload.
In case of any problem , let us know so we can fix it .

### CODE REVIEW

**Comment by mboekhold** [comment]
It seems that he may have been busy, but i'm not sure, regardless i'd recommend refactoring the logic that u made in bot.py into its own class, (similar to what is done with xkcd module import)

**Comment by StylPamp** [comment]
Ok we will work on that.

Edit: Updated!

**Comment by ghost** [comment]
Hey @StylPamp 

Don't commit files inside `__pycache__` folders. Those are generated when the code runs.

Also in bot.py you can use commas to import various modules. 
You can change:
```
from modules import xkcd
from modules import roll
from modules import ping
```
to
```
from modules import xkcd, roll, ping
```
You don't have a limit of commas but it's nice to avoid long lines.

If you have any questions feel free to ask here or at the [discord](https://discord.gg/MsZ9N9n)

**Comment by swapagarwal** [comment]
@StylPamp It'd be great if you could make one PR per feature. 😅
Let me know if you need help on this.

**Pull request closed without merging**
